casv/casv/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^', include('core.urls', namespace='core')),
    url(r'^admin/', include(admin.site.urls)),
)

# Uncomment the next line to serve media files in dev.
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
                            url(r'^__debug__/', include(debug_toolbar.urls)),
                            )

casv/core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from .views import upload_file, logout_view, UserUploads
from .views import AsvDetailView, AsvDeleteView
from .views import CompensacaoDetailView, CompensacaoDeleteView
from .views import AreaSolturaDetailView, AreaSolturaDeleteView
from .views import AsvGeoView, SolturaGeoView, CompensacaoGeoView
from .views import EmbargoDetailView, EmbargoDeleteView
from .views import AutoInfracaoDetailView, AutoInfracaoDeleteView
from .views import EmbargoGeoView, AutoInfracaoGeoView,IbamaPedidoAnuenciaDetailView
from .views import IbamaAnuenciaListView,IbamaConcederAnuenciaView

from .views import DadosAnuenciaMaDetailView,DadosAnuenciaMaDeleteView
from .views import GeomPedidoAnuenciaMaGeoView,GeomAnuenciaConcedidaMaGeoView
from .views import IbamaAnuenciaConcedida,IbamaDadosAnuenciaConcedida
from .views import LoginView,DadosPedidoAnuenciaUsuarioMaView,IbamaDadosAnuenciaMaDeleteView
from .views import IbamaDownloadShpUser


urlpatterns = patterns(
    '',
    url(r'^$', TemplateView.as_view(template_name='base.html'), name='index'),
    
    url(r'^download/shp_user/(?P<processo>\d+)/$',staff_member_required(IbamaDownloadShpUser.as_view()),name='shp-user'),

    url(r'^upload/',
        login_required(upload_file, login_url='/login/'),
        name='upload'),

    url(r'^file-models/',
        TemplateView.as_view(template_name='core/file-models.html'),
        name='file-models'),

    url(r'^login/', LoginView.as_view(), name='login'),

    url(r'^logout/', logout_view, name='logout'),

    url(r'^user-uploads/',
        UserUploads.as_view(),
        name='user-uploads'),

    url(r'^ibama/$',
        staff_member_required(IbamaAnuenciaListView.as_view(),
        login_url='/login/'),
        name='ibama-list'),
    
    url(r'^ibama/concessao/(?P<processo>\d+)/$',
        staff_member_required(IbamaConcederAnuenciaView.as_view(),
        login_url='/login/'),
        name='ibama-concessao'),

    url(r'^ibama/concedidos/$',
        staff_member_required(IbamaAnuenciaConcedida.as_view(),
        login_url='/login/'),
        name='ibama-concedidos'),

    url(r'^ibama/concedidos/(?P<processo>\d+)/$',
        staff_member_required(IbamaDadosAnuenciaConcedida.as_view(),
        login_url='/login/'),
        name='ibama-concedidos-dados'),

    url(r'^ibama/dados-pedido/(?P<processo>\d+)/$',
        staff_member_required(IbamaPedidoAnuenciaDetailView.as_view(),
        login_url='/login/'),
        name='ibama-geo'),

    url(r'^ibama/(?P<processo>\d+)/delete$',
        staff_member_required(IbamaDadosAnuenciaMaDeleteView.as_view(),
        login_url='/login/'),
        name='ibama-delete'),

    url(r'^asv/(?P<pk>\d+)/$',
        AsvDetailView.as_view(),
        name='asv'),

    url(r'^asv/(?P<pk>\d+)/delete/$',
        AsvDeleteView.as_view(),
        name='delete-asv'),

    url(r'^areasoltura/(?P<pk>\d+)/$',
        AreaSolturaDetailView.as_view(),
        name='areasoltura'),

    url(r'^areasoltura/(?P<pk>\d+)/delete/$',
        AreaSolturaDeleteView.as_view(),
        name='delete-areasoltura'),

    url(r'^pedido-anuencia/(?P<processo>\d+)/$',
        DadosPedidoAnuenciaUsuarioMaView.as_view(
        template_name = 'core/pedidoanuenciamataatlantica_detail.html'),
        name='pedido_anuencia'),

    url(r'^pedido-anuencia/(?P<pk>\d+)/delete/$',
        DadosAnuenciaMaDeleteView.as_view(
        template_name = 'core/pedidoanuenciamataatlantica_confirm_delete.html'),
        name='delete-pedido_anuencia'),

    url(r'^pedido-anuencia/geo/(?P<processo>\d+)/$',
        GeomPedidoAnuenciaMaGeoView.as_view(),
        name='geo-pedido_anuencia'),
    
    url(r'^anuencia-concedida/geo/(?P<processo>\d+)/$',
        GeomAnuenciaConcedidaMaGeoView.as_view(),
        name='geo-anuencia_concedida'),

    url(r'^compensacao/(?P<pk>\d+)/$',
        CompensacaoDetailView.as_view(),
        name='compensacao'),

    url(r'^compensacao/(?P<pk>\d+)/delete/$',
        CompensacaoDeleteView.as_view(),
        name='delete-compensacao'),

    url(r'^embargo/(?P<pk>\d+)/$',
        EmbargoDetailView.as_view(),
        name='embargo'),

    url(r'^embargo/(?P<pk>\d+)/delete/$',
        EmbargoDeleteView.as_view(),
        name='delete-embargo'),

    url(r'^infracao/(?P<pk>\d+)/$',
        AutoInfracaoDetailView.as_view(),
        name='infracao'),

    url(r'^infracao/(?P<pk>\d+)/delete/$',
        AutoInfracaoDeleteView.as_view(),
        name='delete-infracao'),

    url(r'^embargo/geo/(?P<pk>\d+)/$',
        EmbargoGeoView.as_view(),
        name='geo-embargo'),

    url(r'^infracao/geo/(?P<pk>\d+)/$',
        AutoInfracaoGeoView.as_view(),
        name='geo-infracao'),

    url(r'^compensacao/geo/(?P<pk>\d+)/$',
        CompensacaoGeoView.as_view(),
        name='geo-compensacao'),

    url(r'^asv/geo/(?P<pk>\d+)/$',
        AsvGeoView.as_view(),
        name='geo-asv'),

    url(r'^areasoltura/geo/(?P<pk>\d+)/$',
        SolturaGeoView.as_view(),
        name='geo-areasoltura'),
    
)

casv/core/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import ugettext as _


class UploadFileForm(forms.Form):
    upload_file = forms.FileField(label=_('Upload file'),required=False)

class ComboboxStatusForm(forms.Form):
    itens  = ['Status','Em Análise','Arquivado','Deferido','Índeferido','Outros']
    Status = forms.ChoiceField(choices=itens) 

casv/core/views.py
import shapefile
import zipfile
import fiona

from datetime import datetime
from collections import OrderedDict
from os import path, mkdir,remove
from shutil import rmtree,make_archive
from shapely.geometry import shape

from rest_framework.generics import RetrieveAPIView
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.authtoken.models import Token
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.gis.geos import Polygon, MultiPolygon
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView, DeleteView,TemplateView
from django.views.generic.list import ListView 
from django.utils.translation import ugettext as _
from django.http import HttpResponse
from django.conf import settings
from shapely.geometry.base import BaseGeometry

from .forms import UploadFileForm,ComboboxStatusForm
from .models import Asv, AreaSoltura
from .models import CompensacaoMataAtlantica,DadosAnuenciaMataAtlantica
from .models import GeomAnuenciaConcedidaMataAtlantica,GeomPedidoAnuenciaMataAtlantica
from .models import AutoInfracaoOEMA, EmbargoOEMA
from .models import UserPermited
from .serializers import CompensacaoSerializer, AsvMaSerializer
from .serializers import AsvSerializer, SolturaSerializer
from .serializers import EmbargoSerializer, AutoInfracaoSerializer
from .serializers import GeomPedidoAnuenciaMaSerializer,GeomAnuenciaConcedidaMaSerializer


class InvalidShapefileError(Exception):

    def __init__(self, message):
        self.message = message


def get_mapping(schema):
    asv = {
        'properties': OrderedDict([
            ('codigo', 'int:10'),
            ('n_autex', 'str:30'),
            ('uf', 'str:2'),
            ('fito', 'str:60'),
            ('nom_prop', 'str:60'),
            ('cpfj_prop', 'str:22'),
            ('detentor', 'str:60'),
            ('cpfj_dete', 'str:22'),
            ('rt', 'str:60'),
            ('cpfj_rt', 'str:22'),
            ('area_ha', 'float:20.15'),
            ('lenha_st', 'float:20.15'),
            ('tora_m', 'float:20.15'),
            ('torete_m', 'float:20.15'),
            ('mourao_m', 'float:20.15'),
            ('data_autex', 'date'),
            ('valido_ate', 'date'),
            ('municipio', 'str:40')
        ]),
        'geometry': 'Polygon'
    }

    asv2 = {
        'properties': OrderedDict([
            ('codigo', 'int:10'),
            ('n_autex', 'str:30'),
            ('uf', 'str:2'),
            ('fito', 'str:60'),
            ('nom_prop', 'str:60'),
            ('cpfj_prop', 'str:22'),
            ('detentor', 'str:60'),
            ('cpfj_dete', 'str:22'),
            ('rt', 'str:60'),
            ('cpfj_rt', 'str:22'),
            ('area_ha', 'float:20.15'),
            ('lenha_st', 'float:20.15'),
            ('tora_m', 'float:20.15'),
            ('torete_m', 'float:20.15'),
            ('mourao_m', 'float:20.15'),
            ('data_autex', 'date'),
            ('valido_ate', 'date'),
            ('municipio', 'str:40')
        ]),
        'geometry': 'Multipolygon'
    }

    asv3 = {
        'properties': OrderedDict([
            ('codigo', 'int:9'),
            ('n_autex', 'str:30'),
            ('uf', 'str:2'),
            ('fito', 'str:60'),
            ('nom_prop', 'str:60'),
            ('cpfj_prop', 'str:22'),
            ('detentor', 'str:60'),
            ('cpfj_dete', 'str:22'),
            ('rt', 'str:60'),
            ('cpfj_rt', 'str:22'),
            ('area_ha', 'float:20'),
            ('lenha_st', 'float:20'),
            ('tora_m', 'float:20'),
            ('torete_m', 'float:20'),
            ('mourao_m', 'float:20'),
            ('data_autex', 'date'),
            ('valido_ate', 'date'),
            ('municipio', 'str:40')
        ]),
        'geometry': 'Polygon'
    }

    asv4 = {
        'properties': OrderedDict([
            ('codigo', 'int:9'),
            ('n_autex', 'str:30'),
            ('uf', 'str:2'),
            ('fito', 'str:60'),
            ('nom_prop', 'str:60'),
            ('cpfj_prop', 'str:22'),
            ('detentor', 'str:60'),
            ('cpfj_dete', 'str:22'),
            ('rt', 'str:60'),
            ('cpfj_rt', 'str:22'),
            ('area_ha', 'float:20'),
            ('lenha_st', 'float:20'),
            ('tora_m', 'float:20'),
            ('torete_m', 'float:20'),
            ('mourao_m', 'float:20'),
            ('data_autex', 'date'),
            ('valido_ate', 'date'),
            ('municipio', 'str:40')
        ]),
        'geometry': 'Multipolygon'
    }

    asv5 = {
        'properties': OrderedDict([
            ('codigo', 'int:9'), 
            ('n_autex', 'str:30'), 
            ('uf', 'str:2'), 
            ('fito', 'str:60'), 
            ('nom_prop', 'str:60'), 
            ('cpfj_prop', 'str:22'), 
            ('detentor', 'str:60'), 
            ('cpfj_dete', 'str:22'), 
            ('rt', 'str:60'), 
            ('cpfj_rt', 'str:22'), 
            ('area_ha', 'float'), 
            ('lenha_st', 'float'), 
            ('tora_m', 'float'), 
            ('torete_m', 'float'), 
            ('mourao_m', 'float'), 
            ('data_autex', 'date'), 
            ('valido_ate', 'date'), 
            ('municipio', 'str:40')
        ]), 
        'geometry': 'Polygon'
    }

    asv6 = {
        'properties': OrderedDict([
            ('codigo', 'int:9'), 
            ('n_autex', 'str:30'), 
            ('uf', 'str:2'), 
            ('fito', 'str:60'), 
            ('nom_prop', 'str:60'), 
            ('cpfj_prop', 'str:22'), 
            ('detentor', 'str:60'), 
            ('cpfj_dete', 'str:22'), 
            ('rt', 'str:60'), 
            ('cpfj_rt', 'str:22'), 
            ('area_ha', 'float'), 
            ('lenha_st', 'float'), 
            ('tora_m', 'float'), 
            ('torete_m', 'float'), 
            ('mourao_m', 'float'), 
            ('data_autex', 'date'), 
            ('valido_ate', 'date'), 
            ('municipio', 'str:40')
        ]), 
        'geometry': 'Multipolygon'
    }

    asv7 = {
        'properties': OrderedDict([
            ('codigo', 'int:9'), 
            ('n_autex', 'str:30'), 
            ('uf', 'str:2'), 
            ('fito', 'str:60'), 
            ('nom_prop', 'str:60'), 
            ('cpfj_prop', 'str:22'), 
            ('detentor', 'str:60'), 
            ('cpfj_dete', 'str:22'), 
            ('rt', 'str:60'), 
            ('cpfj_rt', 'str:22'), 
            ('area_ha', 'float:24.15'), 
            ('lenha_st', 'float:24.15'), 
            ('tora_m', 'float:24.15'), 
            ('torete_m', 'float:24.15'), 
            ('mourao_m', 'float:24.15'), 
            ('data_autex', 'date'), 
            ('valido_ate', 'date'), 
            ('municipio', 'str:40')
        ]),
        'geometry': 'Polygon'
    }

    asv8 = {
        'properties': OrderedDict([
            ('codigo', 'int:9'), 
            ('n_autex', 'str:30'), 
            ('uf', 'str:2'), 
            ('fito', 'str:60'), 
            ('nom_prop', 'str:60'), 
            ('cpfj_prop', 'str:22'), 
            ('detentor', 'str:60'), 
            ('cpfj_dete', 'str:22'), 
            ('rt', 'str:60'), 
            ('cpfj_rt', 'str:22'), 
            ('area_ha', 'float:24.15'), 
            ('lenha_st', 'float:24.15'), 
            ('tora_m', 'float:24.15'), 
            ('torete_m', 'float:24.15'), 
            ('mourao_m', 'float:24.15'), 
            ('data_autex', 'date'), 
            ('valido_ate', 'date'), 
            ('municipio', 'str:40')
        ]),
        'geometry': 'Multipolygon'
    }


    mapping_asv = {
        'codigo': 'codigo',
        'n_autex': 'n_autex',
        'uf': 'uf',
        'fito': 'fito',
        'nom_prop': 'nom_prop',
        'cpfj_prop': 'cpfj_prop',
        'detentor': 'detentor',
        'cpfj_dete': 'cpfj_dete',
        'rt': 'rt',
        'cpfj_rt': 'cpfj_rt',
        'area_ha': 'area_ha',
        'lenha_st': 'lenha_st',
        'tora_m': 'tora_m',
        'torete_m': 'torete_m',
        'mourao_m': 'mourao_m',
        'data_autex': 'data_autex',
        'valido_ate': 'valido_ate',
        'municipio': 'municipio',
    }

    pedido_anuencia_mata_atlantica = {
        'properties': OrderedDict([
            ('processo', 'int:9'),
            ('empreended', 'str:254'),
            ('uf', 'str:2'),
            ('municipio', 'str:254'),
            ('tipo_empre','str:254'),
            ('cpfj', 'str:22'),
            ('urb_met', 'str:3'),
            ('a_veg_prim', 'float:20.15'),
            ('a_est_medi', 'float:20.15'),
            ('a_est_avan','float:20.15'),
            ('obs', 'str:250')
        ]),
        'geometry': 'Polygon'
    }


    mapping_ped_anuencia_mata_atlantica = {
        'processo':'processo',
        'uf':'uf',
        'municipio':'municipio',
        'empreendedor':'empreended',
        'tipo_empreendimento':'tipo_empre',
        'cpfj':'cpfj',
        'area_empreendimento_veg_primaria':'a_veg_prim',
        'area_empreendimento_estagio_medio':'a_est_medi',
        'area_empreendimento_estagio_avancado':'a_est_avan',
        'urbano_metropolitano':'urb_met',
        'observacao':'obs'
    }


    compensacao = {
        'properties': OrderedDict([
            ('processo', 'int:10'),
            ('empreended', 'str:254'),
            ('uf', 'str:2'),
            ('municipio', 'str:254'),
            ('tipo_empre', 'str:254'),
            ('cpfj', 'str:22'),
            ('area_compe', 'float:20.15')
        ]),
        'geometry': 'Polygon'
    }
    
    compensacao2 = {
        'properties': OrderedDict([
            ('processo', 'int:10'),
            ('empreended', 'str:254'),
            ('uf', 'str:2'),
            ('municipio', 'str:254'),
            ('tipo_empre', 'str:254'),
            ('cpfj', 'str:22'),
            ('area_compe', 'float:20.15')

casv/core/templates/core/anuenciaIbama_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block page_title %}
	{% trans 'Delete' %} Pedido de Anuência - Mata Atlântica {{ processo }}?
{% endblock %}

{% block content%}
<p>{% trans 'Are you sure you want to delete' %} <strong>{{ processo }}</strong>?</p>
	<form action="{% url 'core:ibama-delete' processo %}" method="post">{% csrf_token %}
	  <button class="btn btn-success" type="submit">{% trans 'Yes' %}</button>
	  <a class="btn btn-danger" href="{% url 'core:ibama-list' %}">{% trans 'No' %}</a>
	</form>
{% endblock %}

casv/core/templates/core/anuenciaIbama_list.html
{% extends 'base.html' %}
{% load staticfiles %}
 <link href="{% static 'css/casv.css' %}" rel="stylesheet">

{% block page_title %}
    <h1>Em Análise</h1>
{% endblock page_title %}

{% block content %}
{% load i18n %}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Lista de Pedidos de Anuência</h3>
        </div>
        <div class="panel-body">
            <ul class="list-group">
            
            {% for item in in_analisys%}
                <li class="list-group-item">
                    <strong><a href="{% url 'core:ibama-geo' item.processo %}" >{{ item.processo }} </a></strong>
                     - {{ item.data_criacao|date:"d M Y" }} - {% if item.ativo %}Ativo{% else %} Inativo {% endif %}
                    

                    <a class="pull-right" title="Conceder Anuência" href="{% url 'core:ibama-concessao' item.processo %}">
                      <span class="text-success glyphicon glyphicon-check"></span>
                    </a>
                </li>
            {% empty %}
              <div class="alert alert-warning" role="alert">{% trans 'You did not upload any files of this type yet.' %}</div>
            {% endfor %}
            </ul>
        </div>
    </div>

{% endblock %}

casv/core/templates/core/autoinfracaooema_confirm_delete.html
{% extends "core/confirm_delete.html" %}
{% load i18n %}

{% block page_title %}
{% trans 'Delete' %} Auto de Infração {{ object.proc }}?
{% endblock %}

casv/core/templates/core/compensacaomataatlantica_confirm_delete.html
{% extends "core/confirm_delete.html" %}
{% load i18n %}

{% block page_title %}{% trans 'Delete' %} Área de Compensação - Mata Atlântica {{ object }}?{% endblock %}

casv/core/templates/core/confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block page_title %}{% endblock %}

{% block content %}
<p>{% trans 'Are you sure you want to delete' %} <strong>{{ object }}</strong>?</p>
<form action="" method="post">{% csrf_token %}
  <button class="btn btn-success" type="submit">{% trans 'Yes' %}</button>
  <a class="btn btn-danger" href="{% url 'core:user-uploads' %}">{% trans 'No' %}</a>
</form>
{% endblock %}

casv/core/templates/core/login_page.html
{% extends "base.html" %}
{% load i18n %}


<h1>{% block page_title %}{% trans 'Login' %}{% endblock page_title %}</h1>

{% block content %}
  {% if msg %}
    <div class="alert alert-danger" role="alert">{{ msg }}</div>
  {% endif %}
  <div class="col-xs-12 col-md-3">
    {% include 'core/login_form.html' %}
  </div>
{% endblock content %}

casv/core/templates/core/pedidoanuenciamataatlantica_confirm_delete.html
{% extends "core/confirm_delete.html" %}
{% load i18n %}

{% block page_title %}{% trans 'Delete' %} Pedido de Anuência - Mata Atlântica {{ object }}?{% endblock %}

casv/core/templates/core/upload.html
{% extends "base.html" %}
{% load i18n %}


<h1>{% block page_title %}{% trans 'Upload a shape file' %}{% endblock page_title %}</h1>

{% block content %}

    {% if uploaded %}
      {% if success %}

        <div class="alert alert-success" role="alert">
          {% blocktrans count quantity=quantity %}
            You uploaded {{ quantity }} item of {{ type }}.
          {% plural %}
            You uploaded {{ quantity }} items of {{ type }}.
          {% endblocktrans %}
        </div>
      
      {% else %}
        
        <div class="alert alert-danger" role="alert">
          {{ message }}
        </div>
      
      {% endif %}
    {% endif %}

    <p>
      <p>Faça upload de um arquivo zip contendo os arquivos shp, dbf, shx e prj. Veja os
      <a href='{% url 'core:file-models' %}'>{% trans 'file models.' %}</a>
    </p>

    <form enctype="multipart/form-data" action="{% url 'core:upload' %}" method="post">{% csrf_token %}
        {{ form.as_p }}
    
        <input class="btn btn-primary" type="submit" id="enviar" value="Enviar" />
    </form>
{% endblock content %}
{% block extra_js %}
    {% include 'core/validate.html' %}
{% endblock extra_js %}

casv/core/templates/core/user_uploads.html
{% extends "base.html" %}
{% load i18n %}


<h1>
  {% block page_title %}
    {% blocktrans %}Uploads of the user{% endblocktrans %} 
    {{ user.username }}
  {% endblock page_title %}
</h1>

{% block content %}

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Autorização de Supressão de Vegetação</h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        {% for item in user.asv.all %}
          <li class="list-group-item">
            <strong><a href="{% url 'core:asv' item.pk %}" >ID: {{ item.pk }} </a></strong>
             - {{ item.data_criacao|date:"d M Y" }}
            <a class="pull-right" href="{% url 'core:delete-asv' item.pk %}">
              <span class="text-danger glyphicon glyphicon-remove-circle"></span>
            </a>
          </li>
        {% empty %}
          <div class="alert alert-warning" role="alert">{% trans 'You did not upload any files of this type yet.' %}</div>
        {% endfor %}
      </ul>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Pedido de Anuência - Mata Atlântica</h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        {% for item in dados_pedido_anuencia%}
          <li class="list-group-item">
            <strong><a href="{% url 'core:pedido_anuencia' item.processo %}" >ID: {{ item.pk }}</a></strong>
           - {{ item.data_criacao|date:"d M Y" }}
            
            <a class="pull-right" href="{% url 'core:delete-pedido_anuencia' item.pk %}">
              <span class="text-danger glyphicon glyphicon-remove-circle"></span>
            </a>
          </li>
        {% empty %}
          <div class="alert alert-warning" role="alert">{% trans 'You did not upload any files of this type yet.' %}</div>
        {% endfor %}
      </ul>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Área de Compensação - Mata Atlântica</h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        {% for item in user.compensacao.all %}
          <li class="list-group-item">
            <strong><a href="{% url 'core:compensacao' item.pk %}">ID: {{ item.pk }}</a></strong>
            - {{ item.data_criacao|date:"d M Y" }}
            <a class="pull-right" href="{% url 'core:delete-compensacao' item.pk %}">
              <span class="text-danger glyphicon glyphicon-remove-circle"></span>
            </a>
          </li>
        {% empty %}
          <div class="alert alert-warning" role="alert">{% trans 'You did not upload any files of this type yet.' %}</div>
        {% endfor %}
      </ul>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Área de Soltura de Animais Silvestres</h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        {% for item in user.area_soltura.all %}
          <li class="list-group-item">
            <strong><a href="{% url 'core:areasoltura' item.pk %}" >ID: {{ item.pk }}</a></strong>
             - {{ item.data_criacao|date:"d M Y" }}
            <a class="pull-right" href="{% url 'core:delete-areasoltura' item.pk %}">
              <span class="text-danger glyphicon glyphicon-remove-circle"></span>
            </a>
          </li>
        {% empty %}
          <div class="alert alert-warning" role="alert">{% trans 'You did not upload any files of this type yet.' %}</div>
        {% endfor %}
      </ul>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Embargos</h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        {% for item in user.embargo.all %}
          <li class="list-group-item">
            <strong><a href="{% url 'core:embargo' item.pk %}" >ID: {{ item.pk }}</a></strong>
             - {{ item.data_criacao|date:"d M Y" }}
            <a class="pull-right" href="{% url 'core:delete-embargo' item.pk %}">
              <span class="text-danger glyphicon glyphicon-remove-circle"></span>
            </a>
          </li>
        {% empty %}
          <div class="alert alert-warning" role="alert">{% trans 'You did not upload any files of this type yet.' %}</div>
        {% endfor %}
      </ul>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Autos de infração</h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        {% for item in user.infracao.all %}
          <li class="list-group-item">
            <strong><a href="{% url 'core:infracao' item.pk %}" >ID: {{ item.pk }}</a></strong>
             - {{ item.data_criacao|date:"d M Y" }}
            <a class="pull-right" href="{% url 'core:delete-infracao' item.pk %}">
              <span class="text-danger glyphicon glyphicon-remove-circle"></span>
            </a>
          </li>
        {% empty %}
          <div class="alert alert-warning" role="alert">{% trans 'You did not upload any files of this type yet.' %}</div>
        {% endfor %}
      </ul>
    </div>
  </div>
  <br/><br/><br/>
{% endblock content %}