casv/casv/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^', include('core.urls', namespace='core')),
    url(r'^admin/', include(admin.site.urls)),
)

# Uncomment the next line to serve media files in dev.
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
                            url(r'^__debug__/', include(debug_toolbar.urls)),
                            )

casv/core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from .views import upload_file, logout_view, UserUploads
from .views import AsvDetailView, AsvDeleteView
from .views import CompensacaoDetailView, CompensacaoDeleteView
from .views import AreaSolturaDetailView, AreaSolturaDeleteView
from .views import AsvGeoView, SolturaGeoView, CompensacaoGeoView
from .views import EmbargoDetailView, EmbargoDeleteView
from .views import AutoInfracaoDetailView, AutoInfracaoDeleteView
from .views import EmbargoGeoView, AutoInfracaoGeoView,IbamaPedidoAnuenciaDetailView
from .views import IbamaAnuenciaListView,IbamaConcederAnuenciaView

from .views import DadosAnuenciaMaDetailView,DadosAnuenciaMaDeleteView
from .views import GeomPedidoAnuenciaMaGeoView,GeomAnuenciaConcedidaMaGeoView
from .views import IbamaAnuenciaConcedida,IbamaDadosAnuenciaConcedida
from .views import LoginView,DadosPedidoAnuenciaUsuarioMaView,IbamaDadosAnuenciaMaDeleteView
from .views import IbamaDownloadShpUser


urlpatterns = patterns(
    '',
    url(r'^$', TemplateView.as_view(template_name='base.html'), name='index'),
    
    url(r'^download/shp_user/(?P<processo>\d+)/$',staff_member_required(IbamaDownloadShpUser.as_view()),name='shp-user'),

    url(r'^upload/',
        login_required(upload_file, login_url='/login/'),
        name='upload'),

    url(r'^file-models/',
        TemplateView.as_view(template_name='core/file-models.html'),
        name='file-models'),

    url(r'^login/', LoginView.as_view(), name='login'),

    url(r'^logout/', logout_view, name='logout'),

    url(r'^user-uploads/',
        UserUploads.as_view(),
        name='user-uploads'),

    url(r'^ibama/$',
        staff_member_required(IbamaAnuenciaListView.as_view(),
        login_url='/login/'),
        name='ibama-list'),
    
    url(r'^ibama/concessao/(?P<processo>\d+)/$',
        staff_member_required(IbamaConcederAnuenciaView.as_view(),
        login_url='/login/'),
        name='ibama-concessao'),

    url(r'^ibama/concedidos/$',
        staff_member_required(IbamaAnuenciaConcedida.as_view(),
        login_url='/login/'),
        name='ibama-concedidos'),

    url(r'^ibama/concedidos/(?P<processo>\d+)/$',
        staff_member_required(IbamaDadosAnuenciaConcedida.as_view(),
        login_url='/login/'),
        name='ibama-concedidos-dados'),

    url(r'^ibama/dados-pedido/(?P<processo>\d+)/$',
        staff_member_required(IbamaPedidoAnuenciaDetailView.as_view(),
        login_url='/login/'),
        name='ibama-geo'),

    url(r'^ibama/(?P<processo>\d+)/delete$',
        staff_member_required(IbamaDadosAnuenciaMaDeleteView.as_view(),
        login_url='/login/'),
        name='ibama-delete'),

    url(r'^asv/(?P<pk>\d+)/$',
        AsvDetailView.as_view(),
        name='asv'),

    url(r'^asv/(?P<pk>\d+)/delete/$',
        AsvDeleteView.as_view(),
        name='delete-asv'),

    url(r'^areasoltura/(?P<pk>\d+)/$',
        AreaSolturaDetailView.as_view(),
        name='areasoltura'),

    url(r'^areasoltura/(?P<pk>\d+)/delete/$',
        AreaSolturaDeleteView.as_view(),
        name='delete-areasoltura'),

    url(r'^pedido-anuencia/(?P<processo>\d+)/$',
        DadosPedidoAnuenciaUsuarioMaView.as_view(
        template_name = 'core/pedidoanuenciamataatlantica_detail.html'),
        name='pedido_anuencia'),

    url(r'^pedido-anuencia/(?P<pk>\d+)/delete/$',
        DadosAnuenciaMaDeleteView.as_view(
        template_name = 'core/pedidoanuenciamataatlantica_confirm_delete.html'),
        name='delete-pedido_anuencia'),

    url(r'^pedido-anuencia/geo/(?P<processo>\d+)/$',
        GeomPedidoAnuenciaMaGeoView.as_view(),
        name='geo-pedido_anuencia'),
    
    url(r'^anuencia-concedida/geo/(?P<processo>\d+)/$',
        GeomAnuenciaConcedidaMaGeoView.as_view(),
        name='geo-anuencia_concedida'),

    url(r'^compensacao/(?P<pk>\d+)/$',
        CompensacaoDetailView.as_view(),
        name='compensacao'),

    url(r'^compensacao/(?P<pk>\d+)/delete/$',
        CompensacaoDeleteView.as_view(),
        name='delete-compensacao'),

    url(r'^embargo/(?P<pk>\d+)/$',
        EmbargoDetailView.as_view(),
        name='embargo'),

    url(r'^embargo/(?P<pk>\d+)/delete/$',
        EmbargoDeleteView.as_view(),
        name='delete-embargo'),

    url(r'^infracao/(?P<pk>\d+)/$',
        AutoInfracaoDetailView.as_view(),
        name='infracao'),

    url(r'^infracao/(?P<pk>\d+)/delete/$',
        AutoInfracaoDeleteView.as_view(),
        name='delete-infracao'),

    url(r'^embargo/geo/(?P<pk>\d+)/$',
        EmbargoGeoView.as_view(),
        name='geo-embargo'),

    url(r'^infracao/geo/(?P<pk>\d+)/$',
        AutoInfracaoGeoView.as_view(),
        name='geo-infracao'),

    url(r'^compensacao/geo/(?P<pk>\d+)/$',
        CompensacaoGeoView.as_view(),
        name='geo-compensacao'),

    url(r'^asv/geo/(?P<pk>\d+)/$',
        AsvGeoView.as_view(),
        name='geo-asv'),

    url(r'^areasoltura/geo/(?P<pk>\d+)/$',
        SolturaGeoView.as_view(),
        name='geo-areasoltura'),
    
)

casv/templates/base.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}CASV - Cadastro Simplificado de Vetores{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/casv.css' %}" rel="stylesheet">

    <!-- Use this to quickly test CSS changes in a template,
        then move to uploadshape.css -->
    {% block extra_css %}{% endblock extra_css %}
  </head>

  <body>

    <div id="barra-brasil" style="background:#7F7F7F; height: 20px; padding:0 0 0 10px;display:block;">
      <ul id="menu-barra-temp" style="list-style:none;">
        <li style="display:inline; float:left;padding-right:10px; margin-right:10px; border-right:1px solid #EDEDED"><a href="http://brasil.gov.br" style="font-family:sans,sans-serif; text-decoration:none; color:white;">Portal do Governo Brasileiro</a></li>
        <li><a style="font-family:sans,sans-serif; text-decoration:none; color:white;" href="http://epwg.governoeletronico.gov.br/barra/atualize.html">Atualize sua Barra de Governo</a></li>
      </ul>
    </div>

    <div class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand navbar-brand-img" href="{% url 'core:index' %}">
              <img  src="{% static 'images/ibama-logo.png' %}" width="30" height="30" alt="logo"/>
          </a>
          <a class="navbar-brand" href="{% url 'core:index' %}">CASV</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            
            {% if request.user.is_authenticated %}
              
              <li>
                <a href="{% url 'core:upload' %}">
                  <span class="glyphicon glyphicon-upload"></span> {% trans 'Upload File' %}
                </a>
              </li>

              <li>
                <a href="{% url 'core:user-uploads' %}">
                  <span class="glyphicon glyphicon-list"></span> {% trans 'My Uploads' %}
                </a>
              </li>

              <li>
                <a href="{% url 'core:file-models' %}">
                  <span class="glyphicon glyphicon-file"></span> {% trans 'File models' %}
                </a>
              </li>

            {% endif %}
            
            {% if request.user.is_staff %}
              
              <li>
                <a href="{% url 'admin:index' %}">
                  <span class="glyphicon glyphicon-cog"></span> 
                  {% trans 'Administration' %}
                </a>
              </li>

              <li>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <span class="glyphicon glyphicon-wrench"></span> {% trans 'Ibama' %}
                  <span class="caret"></span>
                </a>

                <ul class="dropdown-menu">
                  
                  <li>
                    <a href="{% url 'core:ibama-list' %}">
                    Conceder Anuência
                    </a>
                  </li>
                  
                  <li><a href="{% url 'core:ibama-concedidos' %}">Anuências Concedidas</a></li>
                </ul>

              </li>
            
            {% endif %}
          </ul>
          {% include 'core/login_menu.html' %}
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <h1>{% block page_title %}CASV - Cadastro Simplificado de Vetores{% endblock page_title %}</h1>

      {% block content %}
        <p>Este sistema tem como objetivo receber arquivos shapefile e realizar
        a inserção dos dados em banco.</p>
        {% if request.user.is_authenticated %}
          <p><a class="btn btn-primary" href="{% url 'core:upload' %}">{% trans 'Upload' %}</a></p>
        {% else %}
          <p>Realize o login com seu usuário do IBAMANET.</p>
        {% endif %}
      {% endblock content %}

    </div> <!-- /container -->

    <footer>
      <div class="container">
        <p class="text-muted text-center footer-text">IBAMA - Instituto Brasileiro do Meio Ambiente e dos Recursos Naturais Renováveis</p>
      </div>
    </footer>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script src="//barra.brasil.gov.br/barra.js" type="text/javascript"></script>

    <!-- place project specific Javascript in this file -->
    <script src="{% static 'js/casv.js' %}"></script>

    {% block extra_js %}{% endblock extra_js %}
  </body>
</html>