casv/casv/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^', include('core.urls', namespace='core')),
    url(r'^admin/', include(admin.site.urls)),
)

# Uncomment the next line to serve media files in dev.
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
                            url(r'^__debug__/', include(debug_toolbar.urls)),
                            )

casv/core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from .views import upload_file, logout_view, UserUploads
from .views import AsvDetailView, AsvDeleteView
from .views import CompensacaoDetailView, CompensacaoDeleteView
from .views import AreaSolturaDetailView, AreaSolturaDeleteView
from .views import AsvGeoView, SolturaGeoView, CompensacaoGeoView
from .views import EmbargoDetailView, EmbargoDeleteView
from .views import AutoInfracaoDetailView, AutoInfracaoDeleteView
from .views import EmbargoGeoView, AutoInfracaoGeoView,IbamaPedidoAnuenciaDetailView
from .views import IbamaAnuenciaListView,IbamaConcederAnuenciaView

from .views import DadosAnuenciaMaDetailView,DadosAnuenciaMaDeleteView
from .views import GeomPedidoAnuenciaMaGeoView,GeomAnuenciaConcedidaMaGeoView
from .views import IbamaAnuenciaConcedida,IbamaDadosAnuenciaConcedida
from .views import LoginView,DadosPedidoAnuenciaUsuarioMaView,IbamaDadosAnuenciaMaDeleteView
from .views import IbamaDownloadShpUser


urlpatterns = patterns(
    '',
    url(r'^$', TemplateView.as_view(template_name='base.html'), name='index'),
    
    url(r'^download/shp_user/(?P<processo>\d+)/$',staff_member_required(IbamaDownloadShpUser.as_view()),name='shp-user'),

    url(r'^upload/',
        login_required(upload_file, login_url='/login/'),
        name='upload'),

    url(r'^file-models/',
        TemplateView.as_view(template_name='core/file-models.html'),
        name='file-models'),

    url(r'^login/', LoginView.as_view(), name='login'),

    url(r'^logout/', logout_view, name='logout'),

    url(r'^user-uploads/',
        UserUploads.as_view(),
        name='user-uploads'),

    url(r'^ibama/$',
        staff_member_required(IbamaAnuenciaListView.as_view(),
        login_url='/login/'),
        name='ibama-list'),
    
    url(r'^ibama/concessao/(?P<processo>\d+)/$',
        staff_member_required(IbamaConcederAnuenciaView.as_view(),
        login_url='/login/'),
        name='ibama-concessao'),

    url(r'^ibama/concedidos/$',
        staff_member_required(IbamaAnuenciaConcedida.as_view(),
        login_url='/login/'),
        name='ibama-concedidos'),

    url(r'^ibama/concedidos/(?P<processo>\d+)/$',
        staff_member_required(IbamaDadosAnuenciaConcedida.as_view(),
        login_url='/login/'),
        name='ibama-concedidos-dados'),

    url(r'^ibama/dados-pedido/(?P<processo>\d+)/$',
        staff_member_required(IbamaPedidoAnuenciaDetailView.as_view(),
        login_url='/login/'),
        name='ibama-geo'),

    url(r'^ibama/(?P<processo>\d+)/delete$',
        staff_member_required(IbamaDadosAnuenciaMaDeleteView.as_view(),
        login_url='/login/'),
        name='ibama-delete'),

    url(r'^asv/(?P<pk>\d+)/$',
        AsvDetailView.as_view(),
        name='asv'),

    url(r'^asv/(?P<pk>\d+)/delete/$',
        AsvDeleteView.as_view(),
        name='delete-asv'),

    url(r'^areasoltura/(?P<pk>\d+)/$',
        AreaSolturaDetailView.as_view(),
        name='areasoltura'),

    url(r'^areasoltura/(?P<pk>\d+)/delete/$',
        AreaSolturaDeleteView.as_view(),
        name='delete-areasoltura'),

    url(r'^pedido-anuencia/(?P<processo>\d+)/$',
        DadosPedidoAnuenciaUsuarioMaView.as_view(
        template_name = 'core/pedidoanuenciamataatlantica_detail.html'),
        name='pedido_anuencia'),

    url(r'^pedido-anuencia/(?P<pk>\d+)/delete/$',
        DadosAnuenciaMaDeleteView.as_view(
        template_name = 'core/pedidoanuenciamataatlantica_confirm_delete.html'),
        name='delete-pedido_anuencia'),

    url(r'^pedido-anuencia/geo/(?P<processo>\d+)/$',
        GeomPedidoAnuenciaMaGeoView.as_view(),
        name='geo-pedido_anuencia'),
    
    url(r'^anuencia-concedida/geo/(?P<processo>\d+)/$',
        GeomAnuenciaConcedidaMaGeoView.as_view(),
        name='geo-anuencia_concedida'),

    url(r'^compensacao/(?P<pk>\d+)/$',
        CompensacaoDetailView.as_view(),
        name='compensacao'),

    url(r'^compensacao/(?P<pk>\d+)/delete/$',
        CompensacaoDeleteView.as_view(),
        name='delete-compensacao'),

    url(r'^embargo/(?P<pk>\d+)/$',
        EmbargoDetailView.as_view(),
        name='embargo'),

    url(r'^embargo/(?P<pk>\d+)/delete/$',
        EmbargoDeleteView.as_view(),
        name='delete-embargo'),

    url(r'^infracao/(?P<pk>\d+)/$',
        AutoInfracaoDetailView.as_view(),
        name='infracao'),

    url(r'^infracao/(?P<pk>\d+)/delete/$',
        AutoInfracaoDeleteView.as_view(),
        name='delete-infracao'),

    url(r'^embargo/geo/(?P<pk>\d+)/$',
        EmbargoGeoView.as_view(),
        name='geo-embargo'),

    url(r'^infracao/geo/(?P<pk>\d+)/$',
        AutoInfracaoGeoView.as_view(),
        name='geo-infracao'),

    url(r'^compensacao/geo/(?P<pk>\d+)/$',
        CompensacaoGeoView.as_view(),
        name='geo-compensacao'),

    url(r'^asv/geo/(?P<pk>\d+)/$',
        AsvGeoView.as_view(),
        name='geo-asv'),

    url(r'^areasoltura/geo/(?P<pk>\d+)/$',
        SolturaGeoView.as_view(),
        name='geo-areasoltura'),
    
)

casv/core/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import ugettext as _


class UploadFileForm(forms.Form):
    upload_file = forms.FileField(label=_('Upload file'),required=False)

class ComboboxStatusForm(forms.Form):
    itens  = ['Status','Em Análise','Arquivado','Deferido','Índeferido','Outros']
    Status = forms.ChoiceField(choices=itens) 

casv/core/views.py
import shapefile
import zipfile
import fiona

from datetime import datetime
from collections import OrderedDict
from os import path, mkdir,remove
from shutil import rmtree,make_archive
from shapely.geometry import shape

from rest_framework.generics import RetrieveAPIView
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.authtoken.models import Token
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.gis.geos import Polygon, MultiPolygon
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView, DeleteView,TemplateView
from django.views.generic.list import ListView 
from django.utils.translation import ugettext as _
from django.http import HttpResponse
from django.conf import settings
from shapely.geometry.base import BaseGeometry

from .forms import UploadFileForm,ComboboxStatusForm
from .models import Asv, AreaSoltura
from .models import CompensacaoMataAtlantica,DadosAnuenciaMataAtlantica
from .models import GeomAnuenciaConcedidaMataAtlantica,GeomPedidoAnuenciaMataAtlantica
from .models import AutoInfracaoOEMA, EmbargoOEMA
from .models import UserPermited
from .serializers import CompensacaoSerializer, AsvMaSerializer
from .serializers import AsvSerializer, SolturaSerializer
from .serializers import EmbargoSerializer, AutoInfracaoSerializer
from .serializers import GeomPedidoAnuenciaMaSerializer,GeomAnuenciaConcedidaMaSerializer


class InvalidShapefileError(Exception):

    def __init__(self, message):
        self.message = message


def get_mapping(schema):
    asv = {
        'properties': OrderedDict([
            ('codigo', 'int:10'),
            ('n_autex', 'str:30'),
            ('uf', 'str:2'),
            ('fito', 'str:60'),
            ('nom_prop', 'str:60'),
            ('cpfj_prop', 'str:22'),
            ('detentor', 'str:60'),
            ('cpfj_dete', 'str:22'),
            ('rt', 'str:60'),
            ('cpfj_rt', 'str:22'),
            ('area_ha', 'float:20.15'),
            ('lenha_st', 'float:20.15'),
            ('tora_m', 'float:20.15'),
            ('torete_m', 'float:20.15'),
            ('mourao_m', 'float:20.15'),
            ('data_autex', 'date'),
            ('valido_ate', 'date'),
            ('municipio', 'str:40')
        ]),
        'geometry': 'Polygon'
    }

    asv2 = {
        'properties': OrderedDict([
            ('codigo', 'int:10'),
            ('n_autex', 'str:30'),
            ('uf', 'str:2'),
            ('fito', 'str:60'),
            ('nom_prop', 'str:60'),
            ('cpfj_prop', 'str:22'),
            ('detentor', 'str:60'),
            ('cpfj_dete', 'str:22'),
            ('rt', 'str:60'),
            ('cpfj_rt', 'str:22'),
            ('area_ha', 'float:20.15'),
            ('lenha_st', 'float:20.15'),
            ('tora_m', 'float:20.15'),
            ('torete_m', 'float:20.15'),
            ('mourao_m', 'float:20.15'),
            ('data_autex', 'date'),
            ('valido_ate', 'date'),
            ('municipio', 'str:40')
        ]),
        'geometry': 'Multipolygon'
    }

    asv3 = {
        'properties': OrderedDict([
            ('codigo', 'int:9'),
            ('n_autex', 'str:30'),
            ('uf', 'str:2'),
            ('fito', 'str:60'),
            ('nom_prop', 'str:60'),
            ('cpfj_prop', 'str:22'),
            ('detentor', 'str:60'),
            ('cpfj_dete', 'str:22'),
            ('rt', 'str:60'),
            ('cpfj_rt', 'str:22'),
            ('area_ha', 'float:20'),
            ('lenha_st', 'float:20'),
            ('tora_m', 'float:20'),
            ('torete_m', 'float:20'),
            ('mourao_m', 'float:20'),
            ('data_autex', 'date'),
            ('valido_ate', 'date'),
            ('municipio', 'str:40')
        ]),
        'geometry': 'Polygon'
    }

    asv4 = {
        'properties': OrderedDict([
            ('codigo', 'int:9'),
            ('n_autex', 'str:30'),
            ('uf', 'str:2'),
            ('fito', 'str:60'),
            ('nom_prop', 'str:60'),
            ('cpfj_prop', 'str:22'),
            ('detentor', 'str:60'),
            ('cpfj_dete', 'str:22'),
            ('rt', 'str:60'),
            ('cpfj_rt', 'str:22'),
            ('area_ha', 'float:20'),
            ('lenha_st', 'float:20'),
            ('tora_m', 'float:20'),
            ('torete_m', 'float:20'),
            ('mourao_m', 'float:20'),
            ('data_autex', 'date'),
            ('valido_ate', 'date'),
            ('municipio', 'str:40')
        ]),
        'geometry': 'Multipolygon'
    }

    asv5 = {
        'properties': OrderedDict([
            ('codigo', 'int:9'), 
            ('n_autex', 'str:30'), 
            ('uf', 'str:2'), 
            ('fito', 'str:60'), 
            ('nom_prop', 'str:60'), 
            ('cpfj_prop', 'str:22'), 
            ('detentor', 'str:60'), 
            ('cpfj_dete', 'str:22'), 
            ('rt', 'str:60'), 
            ('cpfj_rt', 'str:22'), 
            ('area_ha', 'float'), 
            ('lenha_st', 'float'), 
            ('tora_m', 'float'), 
            ('torete_m', 'float'), 
            ('mourao_m', 'float'), 
            ('data_autex', 'date'), 
            ('valido_ate', 'date'), 
            ('municipio', 'str:40')
        ]), 
        'geometry': 'Polygon'
    }

    asv6 = {
        'properties': OrderedDict([
            ('codigo', 'int:9'), 
            ('n_autex', 'str:30'), 
            ('uf', 'str:2'), 
            ('fito', 'str:60'), 
            ('nom_prop', 'str:60'), 
            ('cpfj_prop', 'str:22'), 
            ('detentor', 'str:60'), 
            ('cpfj_dete', 'str:22'), 
            ('rt', 'str:60'), 
            ('cpfj_rt', 'str:22'), 
            ('area_ha', 'float'), 
            ('lenha_st', 'float'), 
            ('tora_m', 'float'), 
            ('torete_m', 'float'), 
            ('mourao_m', 'float'), 
            ('data_autex', 'date'), 
            ('valido_ate', 'date'), 
            ('municipio', 'str:40')
        ]), 
        'geometry': 'Multipolygon'
    }

    asv7 = {
        'properties': OrderedDict([
            ('codigo', 'int:9'), 
            ('n_autex', 'str:30'), 
            ('uf', 'str:2'), 
            ('fito', 'str:60'), 
            ('nom_prop', 'str:60'), 
            ('cpfj_prop', 'str:22'), 
            ('detentor', 'str:60'), 
            ('cpfj_dete', 'str:22'), 
            ('rt', 'str:60'), 
            ('cpfj_rt', 'str:22'), 
            ('area_ha', 'float:24.15'), 
            ('lenha_st', 'float:24.15'), 
            ('tora_m', 'float:24.15'), 
            ('torete_m', 'float:24.15'), 
            ('mourao_m', 'float:24.15'), 
            ('data_autex', 'date'), 
            ('valido_ate', 'date'), 
            ('municipio', 'str:40')
        ]),
        'geometry': 'Polygon'
    }

    asv8 = {
        'properties': OrderedDict([
            ('codigo', 'int:9'), 
            ('n_autex', 'str:30'), 
            ('uf', 'str:2'), 
            ('fito', 'str:60'), 
            ('nom_prop', 'str:60'), 
            ('cpfj_prop', 'str:22'), 
            ('detentor', 'str:60'), 
            ('cpfj_dete', 'str:22'), 
            ('rt', 'str:60'), 
            ('cpfj_rt', 'str:22'), 
            ('area_ha', 'float:24.15'), 
            ('lenha_st', 'float:24.15'), 
            ('tora_m', 'float:24.15'), 
            ('torete_m', 'float:24.15'), 
            ('mourao_m', 'float:24.15'), 
            ('data_autex', 'date'), 
            ('valido_ate', 'date'), 
            ('municipio', 'str:40')
        ]),
        'geometry': 'Multipolygon'
    }


    mapping_asv = {
        'codigo': 'codigo',
        'n_autex': 'n_autex',
        'uf': 'uf',
        'fito': 'fito',
        'nom_prop': 'nom_prop',
        'cpfj_prop': 'cpfj_prop',
        'detentor': 'detentor',
        'cpfj_dete': 'cpfj_dete',
        'rt': 'rt',
        'cpfj_rt': 'cpfj_rt',
        'area_ha': 'area_ha',
        'lenha_st': 'lenha_st',
        'tora_m': 'tora_m',
        'torete_m': 'torete_m',
        'mourao_m': 'mourao_m',
        'data_autex': 'data_autex',
        'valido_ate': 'valido_ate',
        'municipio': 'municipio',
    }

    pedido_anuencia_mata_atlantica = {
        'properties': OrderedDict([
            ('processo', 'int:9'),
            ('empreended', 'str:254'),
            ('uf', 'str:2'),
            ('municipio', 'str:254'),
            ('tipo_empre','str:254'),
            ('cpfj', 'str:22'),
            ('urb_met', 'str:3'),
            ('a_veg_prim', 'float:20.15'),
            ('a_est_medi', 'float:20.15'),
            ('a_est_avan','float:20.15'),
            ('obs', 'str:250')
        ]),
        'geometry': 'Polygon'
    }


    mapping_ped_anuencia_mata_atlantica = {
        'processo':'processo',
        'uf':'uf',
        'municipio':'municipio',
        'empreendedor':'empreended',
        'tipo_empreendimento':'tipo_empre',
        'cpfj':'cpfj',
        'area_empreendimento_veg_primaria':'a_veg_prim',
        'area_empreendimento_estagio_medio':'a_est_medi',
        'area_empreendimento_estagio_avancado':'a_est_avan',
        'urbano_metropolitano':'urb_met',
        'observacao':'obs'
    }


    compensacao = {
        'properties': OrderedDict([
            ('processo', 'int:10'),
            ('empreended', 'str:254'),
            ('uf', 'str:2'),
            ('municipio', 'str:254'),
            ('tipo_empre', 'str:254'),
            ('cpfj', 'str:22'),
            ('area_compe', 'float:20.15')
        ]),
        'geometry': 'Polygon'
    }
    
    compensacao2 = {
        'properties': OrderedDict([
            ('processo', 'int:10'),
            ('empreended', 'str:254'),
            ('uf', 'str:2'),
            ('municipio', 'str:254'),
            ('tipo_empre', 'str:254'),
            ('cpfj', 'str:22'),
            ('area_compe', 'float:20.15')

casv/core/templates/base.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}CASV - Cadastro de Simles Vetores{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/casv.css' %}" rel="stylesheet">

    <!-- Use this to quickly test CSS changes in a template,
        then move to uploadshape.css -->
    {% block extra_css %}{% endblock extra_css %}
  </head>

  <body>

    <div id="barra-brasil" style="background:#7F7F7F; height: 20px; padding:0 0 0 10px;display:block;">
      <ul id="menu-barra-temp" style="list-style:none;">
        <li style="display:inline; float:left;padding-right:10px; margin-right:10px; border-right:1px solid #EDEDED"><a href="http://brasil.gov.br" style="font-family:sans,sans-serif; text-decoration:none; color:white;">Portal do Governo Brasileiro</a></li>
        <li><a style="font-family:sans,sans-serif; text-decoration:none; color:white;" href="http://epwg.governoeletronico.gov.br/barra/atualize.html">Atualize sua Barra de Governo</a></li>
      </ul>
    </div>

    <div class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'core:index' %}">CASV</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% if request.user.is_authenticated %}
              <li><a href="{% url 'core:upload' %}"><span class="glyphicon glyphicon-upload"></span> {% trans 'Upload' %}</a></li>
              <li><a href="{% url 'core:user-uploads' request.user.pk %}"><span class="glyphicon glyphicon-list"></span> {% trans 'My Uploads' %}</a></li>
              <li><a href="{% url 'core:file-models' %}"><span class="glyphicon glyphicon-file"></span> {% trans 'File models' %}</a></li>
            {% endif %}
            {% if request.user.is_staff %}
              <li><a href="{% url 'admin:index' %}"><span class="glyphicon glyphicon-cog"></span> {% trans 'Administration' %}</a></li>
            {% endif %}
          </ul>
          {% include 'login_menu.html' %}
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <h1>{% block page_title %}CASV - Cadastro de Simples Vetores{% endblock page_title %}</h1>

      {% block content %}
        <p>Este sistema tem como objetivo receber arquivos shapefile e realizar
        a inserção dos dados em banco.</p>
        {% if request.user.is_authenticated %}
          <p><a class="btn btn-primary" href="{% url 'core:upload' %}">{% trans 'Upload' %}</a></p>
        {% else %}
          <p>Realize o login com seu usuário do IBAMANET.</p>
        {% endif %}
      {% endblock content %}

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script src="//barra.brasil.gov.br/barra.js" type="text/javascript"></script>

    <!-- place project specific Javascript in this file -->
    <script src="{% static 'js/casv.js' %}"></script>

    {% block extra_js %}{% endblock extra_js %}
  </body>
</html>

casv/core/templates/login.html
{% load i18n %}

{% if request.user.is_authenticated %}
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a id="btn-logged" class="dropdown-toggle" href="#" data-toggle="dropdown">
          <span class="glyphicon glyphicon-user"></span> {{ request.user.username }} <strong class="caret"></strong>
        </a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'core:logout' %}">{% trans 'Log out' %}</a></li>
        </ul>
      </li>
    </ul>

{% else %}
  <ul class="nav navbar-nav navbar-right">
    <li class="">
      <a id="btn-login" href="#" data-toggle="modal" data-target="#login"><span class="glyphicon glyphicon-user"></span> Login</a>
    </li>
  </ul>
  {% if msg %}
    {{ msg }}
  {% endif %}
  <div class="modal fade" id="login" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">
            <span aria-hidden="true">&times;</span><span class="sr-only">{% trans 'Close' %}</span>
          </button>
          <h4 class="modal-title">{% trans 'Login' %}</h4>
        </div>
        <div class="modal-body">
          <form action="{% url 'core:login' %}" method="post" role="form">{% csrf_token %}
            {% if next %}
              <input type="hidden" name="next" value="{{ next }}" />
            {% endif %}
            <div class="form-group">
              <label for="username">{% trans 'Username' %}:</label>
              <input type="text" name="username" value="" /><br />
              <label for="password">{% trans 'Password' %}:</label>
              <input type="password" name="password" value="" id="password">
            </div>
            <button type="submit" class="btn btn-default">{% trans 'Login' %}</button>
          </form>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
{% endif %}

casv/core/templates/login_menu.html
{% load i18n %}

{% if request.user.is_authenticated %}
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a id="btn-logged" class="dropdown-toggle" href="#" data-toggle="dropdown">
          <span class="glyphicon glyphicon-user"></span> {{ request.user.username }} <strong class="caret"></strong>
        </a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'core:logout' %}">{% trans 'Log out' %}</a></li>
        </ul>
      </li>
    </ul>

{% else %}
  <ul class="nav navbar-nav navbar-right">
    <li class="">
      <a id="btn-login" href="#" data-toggle="modal" data-target="#login"><span class="glyphicon glyphicon-user"></span> {% trans 'Login' %}</a>
    </li>
  </ul>
  <div class="modal fade" id="login" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">
            <span aria-hidden="true">&times;</span><span class="sr-only">{% trans 'Close' %}</span>
          </button>
          <h4 class="modal-title">{% trans 'Login' %}</h4>
        </div>
        <div class="modal-body">
          {% include 'login_form.html' %}
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
{% endif %}

casv/core/templates/login_page.html
{% extends "base.html" %}
{% load i18n %}


<h1>{% block page_title %}{% trans 'Login' %}{% endblock page_title %}</h1>

{% block content %}
  {% if msg %}
    <div class="alert alert-danger" role="alert">{{ msg }}</div>
  {% endif %}
  <div class="col-xs-12 col-md-3">
    {% include 'login_form.html' %}
  </div>
{% endblock content %}

casv/core/templates/user_uploads.html
{% extends "base.html" %}
{% load i18n %}


<h1>{% block page_title %}{% blocktrans %}Uploads of the user{% endblocktrans %} {{ user.first_name }}{% endblock page_title %}</h1>

{% block content %}
  <div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Autorização de Supressão de Vegetação</h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        {% for item in user.asv.all %}
          <li class="list-group-item"><strong>{% trans 'Code' %}: {{ item }}</strong> - {{ item.data_criacao|date:"d M Y" }}</li>
        {% empty %}
          <div class="alert alert-warning" role="alert">{% trans 'You did not upload any files of this type yet.' %}</div>
        {% endfor %}
      </ul>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Autorização de Supressão de Vegetação - Mata Atlântica</h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        {% for item in user.asvma.all %}
          <li class="list-group-item"><strong>{% trans 'Code' %}: {{ item }}</strong> - {{ item.data_criacao|date:"d M Y" }}</li>
        {% empty %}
          <div class="alert alert-warning" role="alert">{% trans 'You did not upload any files of this type yet.' %}</div>
        {% endfor %}
      </ul>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Área de Compensação - Mata Atlântica</h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        {% for item in user.compensacao.all %}
          <li class="list-group-item"><strong>{% trans 'Code' %}: {{ item }}</strong> - {{ item.data_criacao|date:"d M Y" }}</li>
        {% empty %}
          <div class="alert alert-warning" role="alert">{% trans 'You did not upload any files of this type yet.' %}</div>
        {% endfor %}
      </ul>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Área de Soltura de Animais Silvestres</h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        {% for item in user.area_soltura.all %}
          <li class="list-group-item"><strong>{% trans 'Code' %}: {{ item }}</strong> - {{ item.data_criacao|date:"d M Y" }}</li>
        {% empty %}
          <div class="alert alert-warning" role="alert">{% trans 'You did not upload any files of this type yet.' %}</div>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock content %}